---

- hosts: all
  become: true
  tasks:
  - name: Install updates (Kali)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Kali"

  - name: Install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: update and install apache and php packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Kali servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Kali"
