- name: install apache and php for ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for Kali servers
  tags: apache,kali,apache2
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Kali"

- name: copy default html file for the site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: enable and start the apache service
  tags: enabled
  service:
     name: apache2
     state: started
     enabled: yes
  when: ansible_distribution == "Ubuntu"
