- name: install apache and php packages
  tags: apache,apache2,php
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: copy default html file for the site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: enable and start the apache service
  tags: enabled
  service:
     name: "{{ apache_service }}"
     state: started
     enabled: yes
