- name: add ssh key for user jonathan
  authorized_key:
    user: jonathan
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHtT0ZRyWUYAodpwPZ1SisTJmScLmthjIyb7exxtjmax ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
