- name: install mariadb package (Kali)
  tags: kali,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Kali"

- name: install mariadb package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
